# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f04ca89a010208089ea16eebb3d46fac65542a56ecc39f3a85a7d5fc78175837b00a3277402b0f766e2d4a6a72585db7b57ad406e3649db491948a1e298523d

test:
  secret_key_base: b4745bb0272581b576d9f285e74d7ae3384750bf17ad8ae10c9dbc53b55d89b38cae25e1af62721b549d6e60502c58e8b3658931fed99702a8bf6e93739d1785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
